# Generated by Django 5.2.17 on 2026-10-04 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bios', '0001_initial'),
        ('competitions', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, max_length=20)),
                ('base', models.DecimalField(decimal_places=2, max_digits=15)),
                ('guaranteed', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('period', models.CharField(default='year', max_length=20)),
                ('source', models.CharField(blank=True, max_length=500)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bios.bio')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'indexes': [models.Index(fields=['competition', 'season'], name='money_salar_competi_62cb83_idx')],
            },
        ),
    ]
