# Generated by Django 5.2.17 on 2026-10-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_widen_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='position_group',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
