# Generated by Django 5.2.17 on 2026-10-04 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
        ('money', '0003_position_group'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=100)),
                ('sponsor', models.CharField(max_length=200)),
                ('property', models.CharField(max_length=200)),
                ('start', models.IntegerField(null=True)),
                ('end', models.IntegerField(null=True)),
                ('annual', models.BigIntegerField(null=True)),
                ('total', models.BigIntegerField(null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('note', models.TextField(blank=True)),
                ('sources', models.TextField(blank=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
    ]
