# Generated by Django 5.2.17 on 2026-10-04 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
        ('money', '0004_sponsorship'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=50)),
                ('season', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('value', models.BigIntegerField()),
                ('revenue', models.BigIntegerField(null=True)),
                ('operating_income', models.BigIntegerField(null=True)),
                ('published', models.CharField(blank=True, max_length=10)),
                ('revenue_season', models.IntegerField(null=True)),
                ('sources', models.TextField(blank=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'ordering': ('publisher', 'season', 'rank'),
            },
        ),
    ]
