# Generated by Django 5.2.17 on 2026-10-04 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
        ('money', '0005_valuation'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpansionFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('sources', models.TextField(blank=True)),
                ('awarded', models.IntegerField()),
                ('first_season', models.IntegerField()),
                ('fee', models.BigIntegerField(null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'ordering': ('awarded', 'first_season'),
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('sources', models.TextField(blank=True)),
                ('operator', models.CharField(max_length=300)),
                ('start', models.IntegerField(null=True)),
                ('end', models.IntegerField(null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'ordering': ('team__name', 'start'),
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('sources', models.TextField(blank=True)),
                ('year', models.IntegerField()),
                ('seller', models.CharField(max_length=300)),
                ('buyer', models.CharField(max_length=300)),
                ('stake', models.CharField(blank=True, max_length=100)),
                ('price', models.BigIntegerField(null=True)),
                ('valuation', models.BigIntegerField(null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'ordering': ('year', 'team__name'),
            },
        ),
    ]
