# Generated by Django 5.2.17 on 2026-10-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0006_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorship',
            name='length',
            field=models.IntegerField(null=True),
        ),
    ]
