# Generated by Django 5.2.17 on 2026-10-04 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bios', '0001_initial'),
        ('competitions', '0001_initial'),
        ('money', '0007_sponsorship_length'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('sources', models.TextField(blank=True)),
                ('season', models.IntegerField()),
                ('direction', models.CharField(max_length=10)),
                ('kind', models.CharField(max_length=20)),
                ('from_name', models.CharField(blank=True, max_length=200)),
                ('to_name', models.CharField(blank=True, max_length=200)),
                ('fee', models.BigIntegerField(null=True)),
                ('ceiling', models.BigIntegerField(null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('reported', models.DateField(null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
                ('from_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='teams.team')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bios.bio')),
                ('to_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='teams.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
