# Generated by Django 5.2.17 on 2026-10-04 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
        ('money', '0008_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('salary_budget', models.BigIntegerField(null=True)),
                ('maximum_charge', models.BigIntegerField(null=True)),
                ('senior_minimum', models.BigIntegerField(null=True)),
                ('reserve_minimum', models.BigIntegerField(null=True)),
                ('designated_players', models.IntegerField(null=True)),
                ('general_allocation', models.BigIntegerField(null=True)),
                ('targeted_allocation', models.BigIntegerField(null=True)),
                ('roster', models.IntegerField(null=True)),
                ('sources', models.TextField(blank=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
            ],
            options={
                'unique_together': {('competition', 'season')},
            },
        ),
    ]
