# Generated by Django 5.2.17 on 2026-10-04 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
        ('money', '0009_rule'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetWorth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('sources', models.TextField(blank=True)),
                ('owner', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('net_worth', models.BigIntegerField()),
                ('publisher', models.CharField(max_length=50)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
