# Generated by Django 5.2.17 on 2026-10-04 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0010_net_worth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('slug', models.SlugField(max_length=300, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='networth',
            name='club_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='money.owner'),
        ),
        migrations.AddField(
            model_name='operator',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='money.owner'),
        ),
    ]
