# Generated by Django 5.2.17 on 2026-10-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0011_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='coverage',
            field=models.CharField(default='full', max_length=10),
        ),
    ]
