# Generated by Django 5.2.17 on 2026-10-05 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
        ('money', '0012_salary_coverage'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StadiumCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('sources', models.TextField(blank=True)),
                ('stadium', models.CharField(max_length=200)),
                ('opened', models.IntegerField()),
                ('kind', models.CharField(max_length=10)),
                ('cost', models.BigIntegerField(null=True)),
                ('public', models.BigIntegerField(null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'ordering': ('opened', 'stadium'),
            },
        ),
    ]
