# Generated by Django 5.2.17 on 2026-10-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0013_stadium_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=300)),
                ('pay', models.BigIntegerField(null=True)),
                ('related', models.BigIntegerField(null=True)),
                ('other', models.BigIntegerField(null=True)),
                ('coverage', models.CharField(default='full', max_length=10)),
                ('sources', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('organization', 'year', '-pay'),
            },
        ),
    ]
