# Generated by Django 5.2.17 on 2026-10-05 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
        ('money', '0014_staff_pay'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('sources', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=10)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('start', models.DateField()),
                ('start_precision', models.CharField(max_length=5)),
                ('end', models.DateField(null=True)),
                ('end_precision', models.CharField(blank=True, max_length=5)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'ordering': ('start', 'name'),
            },
        ),
    ]
